### ISSUE TITLE
Unknown BABEL option

### ISSUE THREAD

**Issue by anderson916** [acdlite/redux-promise#24]
It works after removing .babelrc.

**Comment by acdlite** [comment]
Fixed in 0.5.1

**Comment by marcshilling** [comment]
I'm on 0.5.1 and still having this issue.

TransformError: /Development/DiscoveryVR-New/node_modules/redux-promise/node_modules/flux-standard-action/lib/index.js: [BABEL] /Development/DiscoveryVR-New/node_modules/redux-promise/node_modules/flux-standard-action/lib/index.js: Unknown option: /Development/DiscoveryVR-New/node_modules/redux-promise/node_modules/flux-standard-action/.babelrc.stage
